version: "3.3"
services:
  go:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    command: /bin/sh -c "go build main.go && ./main"
    volumes:
      - ./config:/gowork/config
      - ./log:/gowork/log
  mysql:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3310:3306"
    volumes:
      - /home/mysql/conf:/etc/mysql/conf.d
#      - /home/mysql/data:/var/lib/mysql
  redis:
    image: "redis:latest"
    ports:
      - "6378:6379"
    volumes:
      - /home/redis/conf:/usr/local/etc/redis

