app:
  mode: debug
  addr: :8080
web:
  url:
mysql:
  host: mysql
  port: 3306
  username: root
  password: 123456
  dbname: test
  charset: utf8mb4
  MaxIdleConns: 10
  MaxOpenConns: 2
redis:
  host: redis
  port: 6379
  auth:
  db: 0
  poolsize: 10
es:
  host: http://127.0.0.1
  port: 9200
  user:
  password:
mongodb:
  host: mongodb://127.0.0.1
  port: 27017
  user: admin
  password: 123456
log:
  level: info
  file_format: "%Y%m%d"
  max_save_days: 7
  path: log/
rtmp:
  user:
  pass:
  host:
  port:
  nickname:
mq:
  status: false
  subject: tickets
  consumersGroup: tickets-consumer-group