app:
  mode: debug
  addr: :8080
web:
  url:
mysql:
  host: 192.168.56.101
  port: 3306
  username: my_test
  password: 7h2kYWaJGrXzGLK4
  dbname: my_test
  charset: utf8mb4
  MaxIdleConns: 10
  MaxOpenConns: 2
redis:
  host: 192.168.56.101
  port: 6379
  auth:
  db: 0
  poolsize: 10
log:
  level: info
  file_format: "%Y%m%d"
  max_save_days: 7
  path: log/
rtmp:
  user:
  pass:
  host:
  port:
  nickname:
juhe:
  key: